#C:\Users\dixie\AppData\Roaming\Alacritty
#mkdir -p /mnt/c/Users/dixie/AppData/Roaming/Alacritty
#vi /mnt/c/Users/dixie/AppData/Roaming/Alacritty/alacritty.toml
[window]
opacity = 0.77
startup_mode = "Maximized"
decorations = "None"

[shell]
program = "wsl.exe ~ -d Ubuntu-24.04"

[font]
normal.family = "MesloLGLDZ Nerd Font"
size = 10.5

[colors]
# Primary colors
[colors.primary]
background = '#011423'
foreground = '#CBE0F0'

# Cursor colors
[colors.cursor]
text = "#011423"
cursor = "#47FF9C"

# Normal colors
[colors.normal]
black = "#214969"
red = "#E52E2E"
green = "#44FFB1"
yellow = "#FFE073"
blue = "#0FC5ED"
magenta = "#a277ff"
cyan = "#24EAF7"
white = "#24EAF7"

# Bright colors
[colors.bright]
black = "#21717D"
red = "#E52E2E"
green = "#44FFB1"
yellow = "#FFE073"
blue = "#A277FF"
magenta = "#a277ff"
cyan = "#24EAF7"
white = "#24EAF7"
